[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# dunce

[[patches]]
[patches.pattern]
target = "card.lua"
match_indent = true
pattern = '''G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.06*G.SETTINGS.GAMESPEED, blockable = false, blocking = false, func = function()'''
position = "before"
payload = '''
SMODS.calculate_context{wheel_of_fortune_fail = true}
'''
